# Generated by Django 4.1.6 on 2023-02-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_rename_prediction_post_yhat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yhat',
            field=models.FloatField(null=True),
        ),
    ]
