# Generated by Django 4.1.6 on 2023-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=1000)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
