# Generated by Django 4.1.6 on 2023-04-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='response',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
