# Generated by Django 4.1.6 on 2023-04-21 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_questionresponse_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='response',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
